# Generated by Django 5.1.2 on 2024-10-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
