# Generated by Django 5.1.2 on 2024-10-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property_App', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='units',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='property',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
